import PrimitiveTypes

/// EVM logs, which are generated by the LOG0-LOG4 opcodes. Each log consists of an address,
/// a list of topics, and some data.
public struct Logs: Equatable {
    /// The address of the log, which is the address of the contract that generated the log.
    public let address: H160
    /// The topics of the log, which are indexed parameters that can be used for filtering. The first topic is typically the hash of the event signature, and the subsequent topics are the indexed event parameters.
    public let topics: [H256]
    /// The data of the log, which contains the non-indexed event parameters. This is a byte array that can be of arbitrary length.
    public let data: [UInt8]
}
